0no-co/hoofd

- package.json
- yarn.lock
`cross-env` was used for the `test:watch` script, but not listed as dev dependency.
> chore: add missing cross-env dev dependency

- README.md
- __tests__/ssr.useTitleTemplate.test.tsx
- __tests__/useTitleTemplate.test.tsx
- src/dispatcher/index.ts
- src/hooks/useTitleTemplate.ts
- src/index.ts
Implements a new hook: `useTitleTemplate` which can be used to format the output of `useTitle`. The `%s` part of the template will be replaced with `title`.
```js
useTitleTemplate('%s | Site');
useTitle('hooked-head')
// title will be: "hooked-head | Site"
```
> Add useTitleTemplate hook

- src/hooks/useLink.ts
`type` is neither experimental or deprecated, and is seen a lot in the wild.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-type
> Added `type` to LinkOptions

- src/hooks/useTitle.ts
The `useEffect`s used in the `useTitle` hook make use of the `template` variable, but currently doesn't mention them as dependencies. This makes changes to `template` silent and doesn't allow changing the scope (title/template) of `useTitle` dynamically.
> fix(useTitle): Add template to useState dependencies

- README.md
- __tests__/ssr.test.tsx
- __tests__/useAmp.test.tsx
- packages/gatsby-plugin-hoofd/gatsby-ssr.js
- src/dispatcher/index.ts
- src/hooks/useAmp.ts
- src/hooks/useHead.ts
- src/index.ts
- src/utils.ts
Currently this only adds support for the `html.amp` attribute and the script. This also adds it to the DOM in both hooks for services like prerender.io
> Support for the AMP-head metadata

- README.md
- src/dispatcher/index.ts
- src/hooks/useAmp.ts
- src/hooks/useHead.ts
- src/hooks/useLang.ts
- src/hooks/useLink.ts
- src/hooks/useMeta.ts
- src/hooks/useTitle.ts
- src/index.ts
In case this is a feature that you're willing to entertain, I've put together what I think would address #34.
This PR:
- Introduces and exports a new `DispatcherContext` that is seeded with default export of `./dispatcher`.
- Exports the `createDispatcher` function, which is useful for setting up an isolated context provider with a distinct Dispatcher.
- Adjusts individual hooks to obtain a reference to the relevant Dispatcher using hooks instead of the module-level singleton.
Closes #34.
> Support context API

- src/hooks/useScript.ts
Adjusts #31 to use the context API introduced in #35.
Also, marks the `type` property of `ScriptOptions` as optional.
> Adjust useScript to use context API

- README.md
- __tests__/ssr.test.tsx
- __tests__/useScript.test.tsx
- packages/gatsby-plugin-hoofd/gatsby-ssr.js
- src/hooks/useScript.ts
This PR includes the following changes
- Includes ability to add embedded data to the `useScript` hook. Solves #43. 
- Changes for `gatsby-plugin-hoofd` to support this ability.
- Updated SSR test cases to include `useScript` hook.
- Removed unused `amp` variable
>  Support for embedded data with useScript

- packages/gatsby-plugin-hoofd/package.json
I use the plugin with Gatsby v3 for a while. It works great. This small change should remove this warning from the build process:
`Plugin gatsby-plugin-hoofd is not compatible with your gatsby version 3.10.0 - It requires gatsby@^2.0.0`
> feat: support Gatsby v3

- packages/gatsby-plugin-hoofd/package.json
Hey,
Gatsby v4 is out. The APIs your plugin is using didn't have any changes. This small change will remove a warning when installing the plugin.
Thanks a bunch,
Benedikt
> build: support Gatsby v4

- src/types.ts
This allows users to set the (experimental, but very awesome) https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/dns-prefetch rel tag
> add: add dns-prefetch to rel type

- package.json
`.mojs` file doesn't exist in `preact/dist`. I suppose it's a typo and you wanted to reference `.mjs`.
> fix: preact export

- README.md
I noticed that the `metaQueue` return type appears to have changed, to basically mirror what's expected for the `linkQueue`. Thus, I've reflected the same logic here in the README
> Update stringify function in README to mirror linkQueue

- src/dispatcher/index.ts
Fixes #75 
I'm simply guarding against `result[0]` not being available.
As described in the issue, I believe React Concurrent Mode is removing the Meta tag while concurrently re-running `useMeta` which believes it's there
I could be wrong in my assumption of the problem. But overall, this seems to fix it for me!
> Guard against no meta tags being returned in React Concurrent Mode

- __tests__/ssr.test.tsx
- src/dispatcher/index.ts
> escape meta content

- .changeset/empty-kings-compete.md
- __tests__/ssr.test.tsx
- src/dispatcher/index.ts
- src/hooks/useLink.ts
Resolve #69 
Rather than always looking for an existing link we'll assume that when we come from hydration we'll see `data-hoofd: "1"` which we'll then take over and hydrate with. Not entirely sure whether this is a breaking change yet 😅 it does solve our concurrent mode problems
Example: https://codesandbox.io/s/priceless-villani-lletf8?file=/src/App.js:174-239
> make useLink concurrent safe

- .changeset/stupid-bananas-hang.md
- __tests__/ssr.test.tsx
- src/dispatcher/index.ts
During our testing, I noticed that `&#39;` appears in the rendered content when escaping `'`. Looking elsewhere, we see them escaping with `&#x27;` instead. This PR replaces the former with the latter with the hope that it renders `'` correctly
> Use #x27 instead of &#39 to escape single quotes

- .changeset/silver-ads-visit.md
- __tests__/useMeta.test.tsx
- src/dispatcher/index.ts
fixes #90 
@tazsingh @ridwanrsk would you mind testing this in your apps?
<details>
<summary>The code</summary>
import { createContext, useContext, useEffect, useRef, useMemo } from 'react';
function _extends() {
_extends = Object.assign ? Object.assign.bind() : function (target) {
for (var i = 1; i < arguments.length; i++) {
var source = arguments[i];
for (var key in source) {
if (Object.prototype.hasOwnProperty.call(source, key)) {
target[key] = source[key];
}
}
}
return target;
};
return _extends.apply(this, arguments);
}
var isServerSide = typeof document === 'undefined';
var META = 'M';
var TITLE = 'T';
var LINK = 'L';
var TEMPLATE = 'P';
var SCRIPT = 'S';
var applyTitleTemplate = function applyTitleTemplate(title, template) {
return template ? template.replace(/%s/g, title || '') : …
> fix(useTitle): concurrent mode fixes

- README.md
Whilst setting up SSR for our app, I discovered a slight error in the example code for meta tag stringification. The extra set of brackets means that the inner reduce call never returns anything, just undefined. Removing the extra brackets makes the stringification work like a charm 🙌 
Also, thanks so much for a great library! This will probably end up replacing our current rig with `react-helmet-async`.
> Fix tag stringification example

- .changeset/blue-swans-kick.md
- __tests__/useScript.test.tsx
- src/hooks/useScript.ts
I ran into this bug when testing for scripts being removed from the DOM. 
When the script element is first created (L32) it was not assigned to the `script` variable that the useEffect return function is using to remove the element (L57)
> fix(useScript): variable scope bug that stops scripts being unmounted
